[workspace]
members = ["crates/*"]
resolver = "2"

[profile.release]
debug = false
strip = "debuginfo"
lto = true
opt-level = "s"

[workspace.dependencies]
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }

